apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJibll0ZG1samRHOXlPbWRvY0Y4M1lqWkVORVJDYUd0NFdUVkJORnAwVFdoTWFrZEZlalEyT1VweFYzb3lNVFJyUVVFPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson