apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-init-script
  namespace: cinemaabyss
data:
  kong-init.sh: |
    #!/bin/sh
    until curl -s http://proxy-service:8001/status > /dev/null; do
      echo "Ждём, пока Kong станет доступен на :8001..."
      sleep 2
    done

    echo "Kong доступен. Регистрируем сервисы и маршруты..."

    curl -i -X POST http://proxy-service:8001/upstreams \
      --data name=proxy

    curl -i -X POST http://proxy-service:8001/upstreams/proxy/targets \
      --data target=monolith:8080 \
      --data weight=100

    curl -i -X POST http://proxy-service:8001/upstreams/proxy/targets \
      --data target=movies-service:8081 \
      --data weight=0

    curl -i -X POST http://proxy-service:8001/services \
      --data name=load-balanced-service \
      --data url=http://proxy

    curl -i -X POST http://proxy-service:8001/services/load-balanced-service/routes \
      --data paths[]=/ \
      --data strip_path=false

    echo "Конфигурация Kong завершена."