# Global settings
global:
  namespace: cinemaabyss
  domain: cinemaabyss.example.com

# Image pull secrets
imagePullSecrets:
  dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJibll0ZG1samRHOXlPbWRvY0Y4M1lqWkVORVJDYUd0NFdUVkJORnAwVFdoTWFrZEZlalEyT1VweFYzb3lNVFJyUVVFPSIKCQl9Cgl9Cn0=
# Database configuration
database:
  host: postgres
  port: 5432
  name: cinemaabyss
  kong: kong
  user: postgres
  password: cG9zdGdyZXNfcGFzc3dvcmQ=
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

# Monolith configuration
monolith:
  enabled: true
  image:
    repository: ghcr.io/nv-victor/architecture-cinemaabyss/monolith
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8080
    targetPort: 8080
    type: ClusterIP

# Proxy service configuration
proxyService:
  enabled: true
  image:
    repository: kong
    tag: 3.6
  replicas: 1
  service:
    port: 80
    targetPort: 8000

# Movies configuration
moviesService:
  enabled: true
  image:
    repository: ghcr.io/nv-victor/architecture-cinemaabyss/movies-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8081
    targetPort: 8081
    type: ClusterIP


# Events configuration
eventsService:
  enabled: true
  image:
    repository: ghcr.io/nv-victor/architecture-cinemaabyss/events-service
    tag: latest
  replicas: 1
  service:
    port: 8082
    targetPort: 8082

# Kafka configuration
kafka:
  enabled: true
  image:
    repository: wurstmeister/kafka
    tag: 2.13-2.7.0
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  persistence:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
  topics:
    - name: movie-events
      partitions: 1
      replicationFactor: 1
    - name: user-events
      partitions: 1
      replicationFactor: 1
    - name: payment-events
      partitions: 1
      replicationFactor: 1

# Zookeeper configuration
zookeeper:
  enabled: true
  image:
    repository: wurstmeister/zookeeper
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    host: cinemaabyss.example.com
    hostKafkaUi: kafka-ui.cinemaabyss.example.com

# Application configuration
config:
  # Strangler Fig configuration
  gradualMigration: "true"
  moviesMigrationPercent: "100"