@startuml C4_Elements

!include ./C4-PlantUML-Git/C4_Component.puml

title Диаграмма стратегического планирования Кинобездны

Container_Boundary(CinemaManagement, "Домен: Управление кинотеатром") {
  Component(RecommendationMng, "Управление рекомендациями", "Context")
  Component(MoviesMng, "Управление фильмами", "Context")
  Component(MoviesWth, "Просмотр фильмов", "Context")
}

Container_Boundary(SubscriptionManagement, "Домен: Управление подписками") {
  Component(PaymentMng, "Обработка платежей", "Context")
  Component(UserMng, "Управление пользователями", "Context")
  Component(SubscriptionMng, "Управление подписками", "Context")
}

Lay_R(MoviesMng,MoviesWth)
Lay_R(UserMng,SubscriptionMng)

@enduml
